# Generated by Django 4.2.3 on 2023-07-25 11:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'entreprise")),
                ('website', models.URLField(blank=True, verbose_name="Site web de l'entreprise")),
                ('city', models.CharField(blank=True, default='Unknown', max_length=100, verbose_name="Ville de l'entreprise")),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message="L'adresse e-mail n'est pas valide.")], verbose_name="Adresse e-mail de l'entreprise")),
                ('physical_address', models.CharField(blank=True, max_length=100, verbose_name="Adresse physique de l'entreprise")),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Nom de la personne à contacter')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, verbose_name='Titre du poste')),
                ('job_description', models.TextField(blank=True, verbose_name='Description du poste')),
                ('job_location', models.CharField(blank=True, max_length=100, verbose_name='Lieu du poste')),
                ('job_type', models.CharField(blank=True, choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Alternance', 'Alternance'), ('Stage', 'Stage'), ('Freelance', 'Freelance')], max_length=100, verbose_name='Type de poste')),
                ('job_site', models.CharField(blank=True, max_length=100, verbose_name='Site du poste')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ajout")),
                ('job_link', models.CharField(blank=True, default='', max_length=255, verbose_name="Lien vers l'annonce")),
                ('contact_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de contact')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favori')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_ads', to='jobportal.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': "Annonce d'emploi",
                'verbose_name_plural': "Annonces d'emploi",
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='jobportal.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.ManyToManyField(blank=True, to='jobportal.note', verbose_name='Notes'),
        ),
    ]
