# Generated by Django 4.2.3 on 2023-08-20 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0003_remove_profile_location_profile_age_profile_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='jobad',
            options={},
        ),
        migrations.RemoveField(
            model_name='company',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='university',
        ),
        migrations.AddField(
            model_name='note',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobportal.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='email_address',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='physical_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportal.company'),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='job_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='job_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='job_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='job_site',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='job_type',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AddField(
            model_name='profile',
            name='educations',
            field=models.ManyToManyField(blank=True, to='jobportal.education'),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.ManyToManyField(blank=True, to='jobportal.language'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='jobportal.skill'),
        ),
    ]
